### ISSUE TITLE
Test context completion state sanity checks

### ISSUE THREAD

**Issue by LiamClarkeNZ** [eclipse-vertx/vertx-junit5#106] opened 2021-06-14 04:29 UTC
#### Describe the feature

`VertxTestContext` throws an appropriate exception to signal an invalid state if a new checkpoint or handler (`succeeding`/`failing`/`verify` etc.) is created when the test context is already completed (when the `releaseLatch` inside the context  equals 0). 

#### Use cases

I'm creating this feature request because I recently hit an issue in the Strimzi codebase where tests were passing despite deliberate failures being introduced into their `context.verify()` blocks. 

This occurred because a single checkpoint had been created and then flagged as completed before the async Vert.x code under test was actually exercised, and when the last remaining checkpoint is flagged, the context is marked as completed. Further checkpoints were subsequently created, but whether or not they were flagged was irrelevant, as the release latch was already at zero. Likewise, if any failures had been caught, they would only be registered with the test context if it isn't marked as completed.

As all the code under test was running in a separate thread,  the unit test method didn't block, and when `VertxExtension` used `awaitsCompletion` in an `afterEach` context, to wait for the async code under test, no blocking occurred, because the test context was already marked as completed, so the `context.verify()` block never managed to run before all threads exited, and as such never managed to throw an `AssertionError` that would cause the test to fail.

While the usage of the checkpoint I encountered was not how checkpoints are intended to be used, I would like add checks to catch this edge case to prevent tests passing when they should fail.

#### Contribution

I am very willing to submit a PR for this, I just wanted to check with the contributors that I a) understand the logic flow of the `VertxExtension` correctly and b) that I am not missing a use case that needs to create handlers and checkpoints after a test context is complete.

#### Reproduction case

https://gist.github.com/LiamClarkeNZ/945c37ab094ae88ca47b279e9b3e7448

```
package io.strimzi.operator;

import io.vertx.core.Future;
import io.vertx.junit5.Checkpoint;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(VertxExtension.class)
public class ReproductionTest {

    @Test
    void reproduceCheckpointIssues(VertxTestContext context) {

        Checkpoint prematurelyFlagged = context.checkpoint();
        prematurelyFlagged.flag();
        
        Checkpoint neverCompletedCheckpointShouldTimeoutTestButDoesNot = context.checkpoint();
        
        Future.succeededFuture("Example").onComplete(context.succeeding(example -> context.verify(() -> {
            assertEquals("Break this assertion", example);
            throw new RuntimeException("Die");
        })));
    }
}
```        
**Output:**

```
Process finished with exit code 0
```

**Example desired output:**

```
java.lang.IllegalStateException: Cannot create new checkpoint on already completed test context

<stacktrace>

Process finished with exit code 255
```

_Or_

```
java.lang.IllegalStateException: Cannot create new succeeding() handler on already completed test context

<stacktrace>

Process finished with exit code 255
```

**Comment by jponge** [comment] 2021-06-25 07:01
Sorry for the delay.

Yes please feel-free to open a PR and we'll check this.

**Comment by LiamClarkeNZ** [comment] 2021-06-26 06:25
@jponge thanks :) Quick question, what language level should I be using, 8 or 11?

**Comment by vietj** [comment] 2021-06-29 08:10
Java 8

**Comment by julianladisch** [comment] 2022-10-15 21:03
Vert.x 4.2.6 fixes the reproduction case posted in this issue's description.
The reproduction case has been fixed by #114.
I suggest to close this issue as duplicate of #113.

**Comment by LiamClarkeNZ** [comment] 2022-10-16 22:41
@julianladisch - #114 is brilliant, but, there's still one erroneous case - you still have the ability to accidentally mark a context as completed successfully depending on how you create and flag checkpoints.

Here's another reproduction test to demonstrate, the particular test where `VertxExtension#afterEach` should throw a `TimeoutException`, but doesn't, is `doesNotTimeoutAsExpected()`. I've done horrible things to manually plumb in the `VertxTestExtension` so I can make assertions on its behaviour.

Output of running that test case: 

```
Context is completed after first flag? true

org.opentest4j.AssertionFailedError: Expected java.util.concurrent.TimeoutException to be thrown, but nothing was thrown.

	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3007)
```

So, I propose that I dramatically reduce the scope of my PR (and you're right, it was very wide-reaching, so I'm very glad for #114, as it handles it far nicer than my approach did) and just throw an exception if a checkpoint is created after the context is completed. How does that sound to you?

```kotlin
package com.example.starter

import io.vertx.junit5.Timeout
import io.vertx.junit5.VertxExtension
import io.vertx.junit5.VertxTestContext
import org.junit.jupiter.api.*
import org.junit.jupiter.api.extension.*
import java.lang.reflect.Parameter
import java.util.*
import java.util.concurrent.TimeUnit
import java.util.concurrent.TimeoutException

class ReproductionTest {

  @RegisterExtension
  @JvmField
  val extensionContextCollector = ExtensionContextCollector()

  lateinit var vertxExtension: VertxExtension
  lateinit var context: VertxTestContext

  @BeforeEach
  fun setup() {
    vertxExtension = VertxExtension()
    context = vertxExtension.resolveParameter(GiveMeAVertxContextPlease(), extensionContextCollector.context) as VertxTestContext
  }

  @Test
  @Timeout(1, timeUnit = TimeUnit.SECONDS)
  fun timesOutAsExpected() {
    val firstFlag = context.checkpoint()
    val secondFlag = context.checkpoint()

    firstFlag.flag()
    //secondFlag.flag()

    // Second checkpoint is never flagged, so test fails on timeout
    assertThrows<TimeoutException> { vertxExtension.afterEach(extensionContextCollector.context) }
  }

  @Test
  @Timeout(1, timeUnit = TimeUnit.SECONDS)
  fun succeedsAsExpected() {
    val firstFlag = context.checkpoint()
    val secondFlag = context.checkpoint()
    firstFlag.flag()
    println("Context is completed after first flag? ${context.completed()}")
    secondFlag.flag()

    // Second checkpoint is flagged, test passes
    assertDoesNotThrow { vertxExtension.afterEach(extensionContextCollector.context) }
  }

  @Test
  @Timeout(1, timeUnit = TimeUnit.SECONDS)
  fun doesNotTimeoutAsExpected() {
    val firstFlag = context.checkpoint()
    firstFlag.flag()
    println("Context is completed after first flag? ${context.completed()}")
    val secondFlag = context.checkpoint()
    // secondFlag.flag()

    // Second checkpoint never flagged, test should time out, but does not
    assertThrows<TimeoutException>{ vertxExtension.afterEach(extensionContextCollector.context) }
  }

  @Test
  @Timeout(1, timeUnit = TimeUnit.SECONDS)
  fun thisCaseIsFixedThough() {
    val firstFlag = context.checkpoint()
    firstFlag.flag()

    context.verify { fail("X") }
    assertThrows<AssertionError>{ vertxExtension.afterEach(extensionContextCollector.context) }
  }
}

class ExtensionContextCollector : BeforeEachCallback {
  lateinit var context: ExtensionContext

  override fun beforeEach(context: ExtensionContext) {
    this.context = context
  }

}

class GiveMeAVertxContextPlease : ParameterContext {

  fun spec(context: VertxTestContext) {
    // NO-OP just here for reflection fun
  }

  override fun getParameter(): Parameter {
    return this.javaClass.getMethod("spec", VertxTestContext::class.java).parameters[0]
  }

  override fun getIndex(): Int {
    TODO("Not yet implemented")
  }

  override fun getTarget(): Optional<Any> {
    TODO("Not yet implemented")
  }

  override fun isAnnotated(annotationType: Class<out Annotation>?): Boolean {
    TODO("Not yet implemented")
  }

  override fun <A : Annotation?> findAnnotation(annotationType: Class<A>?): Optional<A> {
    TODO("Not yet implemented")
  }

  override fun <A : Annotation?> findRepeatableAnnotations(annotationType: Class<A>?): MutableList<A> {
    TODO("Not yet implemented")
  }

}

```

**Comment by tsegismont** [comment] 2023-01-05 09:25
I believe it's fine to throw an ISE if the user tries to create a checkpoint after the context is completed.

If you're ok with that @jponge , I'll go ahead and make the change, then close this issue.

**Comment by jponge** [comment] 2023-01-05 10:42
If it's _creation_ then yes 👍

**Comment by LiamClarkeNZ** [comment] 2023-01-05 12:10
Brilliant, thanks @tsegismont.

**Closed** 2023-01-05 17:34 UTC
Labels: enhancement, help wanted
